server:
  port: 80  #配置端口
logging: #日志的配置
  file: log/server.log
  level:
    ye.guo.huang.jwt.mapper : DEBUG
spring:
  rabbitmq:
    host : 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jwt?characterEncoding=utf8
    username: root
    password: root
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    date-format : yyyy-MM-dd HH:mm:ss   #有特殊需要可以在实体类上的字段+ @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd") @DateTimeFormat(pattern="yyyy-MM-dd")
    time-zone : GMT+8
#  devtools:  #添加那个目录的文件需要restart
#    restart:
#      additional-paths: src/main/java

  session:
    store-type: none #如果使用redis存储session:spring.session.store-type=redis
  cache:
    type: REDIS

  redis:
    #################redis基础配置#################
    database: 5
    host: 127.0.0.1
#    password:
    port: 6379
    timeout: 3000
    #################redis线程池设置#################
    pool:
      max-idle: 500 # 连接池中的最大空闲连接，默认值也是8。
      min-idle: 50
      max-active: 2000  # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: 1000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
#################redis哨兵设置#################
# Redis服务器master的名字
#spring.redis.sentinel.master=master8026
# redis-sentinel的配置地址和端口
#spring.redis.sentinel.nodes=10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: ye.guo.huang.jwt.pojo  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

constant:
  filepath : D:\09_software\50_intellj idea\Iprodect\spring-boot-chapter\jwt\files
  nonceStr: 5K8264ILTKCH16CQ2502SI8ZNMTM67VS
  appid: wxd0ad6e09b4f09a2awxd0ad6e09b4f09a2a
  AppSecret: 919f06b91b6adbe682c0bd9edc0a008f


